spring:
  application:
    name: yeguoAPI-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: 123456
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session
  session:
    timeout: 86400
    store-type: redis

  # redis
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  lettuce:
    pool:
      max-active: 8        # 连接池最大连接数(使用负值表示没有限制） 默认8
      max-wait: -1         #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
      max-idle: 8          #连接池最大空闲连接 默认8
      min-idle: 0          #连接池最小空闲连接 默认 0
  timeout: 5000            # 超时时间

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
# server
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yeguo.yeguoapi.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#dubbo:
#  application:
#    name: dubbo-springboot-provider
#    logger: slf4j
#  protocol:
#    name: tri
#    port: 50052
#  registry:
#    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
#    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848